"""empty message

Revision ID: 2ae208361ac7
Revises: 529c62c0acdc
Create Date: 2024-03-06 12:16:37.787051

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2ae208361ac7'
down_revision = '529c62c0acdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE message DROP CONSTRAINT fk_chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alem