"""empty message

Revision ID: 2ae208361ac7
Revises: 529c62c0acdc
Create Date: 2024-03-06 12:16:37.787051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae208361ac7'
down_revision = '529c62c0acdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_chats_user1_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chats_user2_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chats_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_chats_receiver_id_users'), 'users', ['receiver_id'], ['id'])
        batch_op.drop_column('user1_id')
        batch_op.drop_column('user2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user2_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user1_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_chats_receiver_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_chats_sender_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_chats_user2_id_users', 'users', ['user2_id'], ['id'])
        batch_op.create_foreign_key('fk_chats_user1_id_users', 'users', ['user1_id'], ['id'])
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
