"""empty message

Revision ID: 529c62c0acdc
Revises: a8580dd72ce4
Create Date: 2024-03-06 12:04:09.824600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529c62c0acdc'
down_revision = 'a8580dd72ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_messages_chat_id_chats'), 'chats', ['chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_chat_id_chats'), type_='foreignkey')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
