"""empty message

Revision ID: b5bc030caaec
Revises: 9bd49fb40640
Create Date: 2024-03-05 17:24:44.080472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bc030caaec'
down_revision = '9bd49fb40640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_messages_animal_id_animals'), 'animals', ['animal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_animal_id_animals'), type_='foreignkey')
        batch_op.drop_column('animal_id')

    # ### end Alembic commands ###
