"""empty message

Revision ID: fb444727ca85
Revises: 2ae208361ac7
Create Date: 2024-03-06 16:06:50.161870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb444727ca85'
down_revision = '2ae208361ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
        

    # ### end Alembic commands ###